### ISSUE TITLE
Элемента <date> не существует

### ISSUE THREAD

**Issue by pepelsbey** [Jahonta/php-project#1]
Зато есть элемент `<time>` с атрибутом `datetime`, [см. спецификацию](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-time-element).

```php
<article class="post">
  <h2 class="post-title"><?= $post['title'] ?></h2>
  <date class="post-date"><?= $post['date'] ?></date>
  <div class="post-content"><?= $post['content'] ?></div>
</article>
```

https://github.com/Jahonta/php-project/blob/328c82b2f11dae266763ef6034638cec70cae6cc/components/post-content.php#L3

https://github.com/Jahonta/php-project/blob/328c82b2f11dae266763ef6034638cec70cae6cc/components/feed.php#L13

https://github.com/Jahonta/php-project/blob/328c82b2f11dae266763ef6034638cec70cae6cc/components/post-content.php#L3

https://github.com/Jahonta/php-project/blob/328c82b2f11dae266763ef6034638cec70cae6cc/style.css#L165

**Comment by Jahonta** [comment]
fixed
