### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by frexin** [Jahonta/php-project#4]
https://github.com/Jahonta/php-project/blob/fa6f3697611f5bc91a9903a8598e5458ebb3c1ef/index.php#L6

Здесь будет ошибка обращения к несуществующему индексу

**Comment by Jahonta** [comment]
То есть лучше так?
 `$page = isset($_GET['page']) ? $_GET['page'] : 1; `

**Comment by frexin** [comment]
да, так можно

**Comment by Jahonta** [comment]
Спасибо!

fixed
